### ISSUE TITLE
Untying frontend from mapping stack

### ISSUE THREAD

**Issue by wuehr1999** [107-systems/l3xz-mapping#14]
<a href="https://107-systems.org/"><img align="right" src="https://raw.githubusercontent.com/107-systems/.github/main/logo/107-systems.png" width="15%"></a>

### ⚡ Untying frontend from mapping stack

**Please Describe The Problem To Be Solved**
The web based frontend is included in the mapping repository, but there is no direct dependency.

**(Optional): Suggest A Solution**
Move the frontend to https://github.com/107-systems/l3xz_frontend and do refactoring work in the new repository.

**Comment by aentinger** [comment]
I suppose moving the webgui to the https://github.com/107-systems/l3xz_frontend is mostly done :wink: .

That leaves with removing the webgui from the mapping package, amirite?

**Comment by wuehr1999** [comment]
Hi @aentinger, the webgui is already removed in the development branch.
